### ISSUE TITLE
这个下载相片，相册都不全，如果相册设置为好友可见，下载不了

### ISSUE THREAD

**Issue by kylewuwu** [youngytj/Qzone_Photo#10]
这个下载相片，相册都不全，如果相册设置为好友可见，下载不了， 有些图片也下载不全

**Comment by tianjyan** [comment]
当然，仅支持[下载公开相册](https://github.com/youngytj/Qzone_Photo#简介)

**Comment by kylewuwu** [comment]
那 下载 好友可见的有没有办法呀， 有些相册图片下载不全

**Comment by tianjyan** [comment]
关于好友可见的问题，你是指你不是好友，但是想下载人家相册吗？然后有些相册下载不全能提供复现步骤吗？

**Comment by kylewuwu** [comment]
我现在就是想下载我的好友相册的图片，但下载不了

**Comment by youngytj** [comment]
嗨，好友可见的意思是不是:
1. 你是ta的好友，并且你能在浏览器访问，但如果非ta的好友，就访问不到，如果是这种情形是下载不了的，因为这不属于公开相册；
2. 你是ta的好友，但ta设置了你不可见，这种情形也是下载不了的，理由同上。

**Comment by tianjyan** [comment]
你的好友相册你能在浏览器中正常访问吗？

**Comment by kylewuwu** [comment]
是好友可以见的相册，只要是他的好友就可以正常访问的相册

**Comment by tianjyan** [comment]
@kylewuwu 你好，我更新了下抓数据的地址，换成https的了，Branch在[这里](https://github.com/youngytj/Qzone_Photo/tree/develop)。你可以测试下载好友可见的相册。

**Comment by kylewuwu** [comment]
多谢！@youngytj 想请教一下  抓数据的地址  是怎么分析出来的吗，我通过 F12 分析，没有头绪 ，地址里面的参数值 一直找不到是重哪里是哪里的代码产生的

**Comment by tianjyan** [comment]
解决你的问题了吗？@kylewuwu 其实我也是用Chrome抓的，Url不一样可能是因为用户不一样吧。这个没啥技术在里面，无非就多抓数据，多对比，猜想验证得出结论。

**Comment by fooofei** [comment]
@kylewuwu  我的分析过程有两点， 看看是否具有参考性：

1. 进入某人 Qzone 时一直 F12 开启开发者模式，打开 network 那一页，且保留日志，一直查看我们网页访问的 url 地址，会一直更新到列表里；

2. 在进入某个人的相册时候，观察 Chrome 监控到的新增的 url 地址，应该能看到端倪，比如 album ，photos 这样的关键字，然后在 Chrome 的 url 列表里，把可疑的每一个都通过右键去验证， Open In New Tab ，在新标签中打开，查看 url 返回值，具有返回 json 的 url 应该格外关注。

以上是我的分析策略。

**Comment by kylewuwu** [comment]
@youngytj @fooofei   非常感谢！ 我这边初步测试可以解决我的问题。
