### ISSUE TITLE
遇到照片名为空便无法下载

### ISSUE THREAD

**Issue by cherinyy** [youngytj/Qzone_Photo#13]
遇到照片名为空便无法下载
另外Python3+无法正常使用，提示：SyntaxError: Missing parentheses in call to 'print'

**Comment by cherinyy** [comment]
另外也不知道什么原因我这边下载多了就会timeout。
貌似是图片比较大。

**Comment by tianjyan** [comment]
倒是从来没想过支持python3，因为python3和python2不兼容，如果要正常使用，请使用python2。

**Comment by tianjyan** [comment]
图片其实不会下载原图的，一般就几百K的样子，现在超时设置是8s，如果超时太多可以修改超时时间以后再尝试。

**Comment by cherinyy** [comment]
不下载原图的呀......

**Comment by tianjyan** [comment]
Hi @872517414 我修复了空文件名不能保持的问题，能再试一下吗？谢谢

**Comment by tianjyan** [comment]
Close this issue as no further feedback.
