### ISSUE TITLE
能否添加暂停或重试功能呢？

### ISSUE THREAD

**Issue by Sion2015** [youngytj/Qzone_Photo#2]
大批量下载的时候网断了就只能从最开始重新下。

**Comment by tianjyan** [comment]
看来你个人相册比较多。因为比较忙，等我有时间可能加入一个下载队列，可以进行并行下载，重试等。如果有兴趣可以fork并自己添加这些代码。

**Comment by tianjyan** [comment]
@Sion2015 Hi, 我在PR #3 里面加了队列和重试的机制。你可以拉最新的master代码尝试下。你可以新建多个worker来处理queue里面的数据。
